spring:
  application:
    name: spectrum-gateway
  cloud:
    gcp:
      project-id: ascendant-acre-473320-g6
    gateway:
      server:
        webmvc:
          routes:
            - id: spectrum-ai-server
              uri: http://spectrum-ai-server.dev.svc.cluster.local:8080
              predicates:
                - Path=/ai-server/**
              filters:
                - RewritePath=/ai-server/(?<segment>.*), /${segment}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans

logging:
  level:
    org.springframework.cloud.gateway: DEBUG